site_name: iters
site_author: nekitdev
site_description: Composable external iteration.

repo_name: nekitdev/iters
repo_url: https://github.com/nekitdev/iters

remote_branch: github-pages

nav:
  - Index: "index.md"
  - Predicates: "predicates.md"
  - Reference:
      - Iterators: "reference/iters.md"
      - Utilities: "reference/utils.md"
      - Wraps: "reference/wraps.md"
      - Mappings: "reference/mappings.md"
      - Ordered Sets: "reference/ordered_sets.md"
      - Typing: "reference/typing.md"
  - Changelog: "changelog.md"
  - Security: "security.md"
  - Code of Conduct: "code_of_conduct.md"
  - Contributing: "contributing.md"

watch:
  - docs
  - src

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate

      primary: deep purple
      accent: light blue

      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default

      primary: light blue
      accent: deep purple

      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

plugins:
  - search

  - mkdocstrings:
      handlers:
        python:
          options:
            members_order: source
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_signature_annotations: true

          import:
            - https://docs.python.org/3/objects.inv
            - https://nekitdev.github.io/orderings/objects.inv
            - https://nekitdev.github.io/wraps/objects.inv
            - https://nekitdev.github.io/iters-collections/objects.inv
            - https://nekitdev.github.io/iters-async/objects.inv

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
